apiVersion: v1
kind: Service
metadata:
  name:springbootDemo-service
spec:
  type:NodePort
  selector:
    app:springbootDemo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 3008
  containers:
  - name: springbootdemo
    image: springbootdemo 
    imagePullPolicy: Never
